# Generated by Django 3.2.3 on 2021-06-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_data_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='text',
        ),
        migrations.AddField(
            model_name='data',
            name='age',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='data',
            name='mail',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='data',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='data',
            name='num',
            field=models.CharField(default='', max_length=10),
        ),
    ]
